version: "3.3"

services:
  ################################################
  ####        Traefik Proxy Setup           #####
  ###############################################
  traefik:
    image: traefik:v2.9
    restart: always
    container_name: traefik_planandeatwell

    ports:
      - "80:80" # <== http
      - "8080:8080" # <== :8080 is where the dashboard runs on
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
      # - ./infra/traefik.toml:/traefik.toml # static config file
    # labels:
    #### Labels define the behavior and rules of the traefik proxy for this container ####
    # - "traefik.enable=true" # <== Enable traefik on itself to view dashboard and assign subdomain to view it
    # - "traefik.http.routers.revproxy.rule=Host(`traefik.localhost`)" # <== Setting the domain for the dashboard
    # - "traefik.http.routers.revproxy.service=api@internal" # <== Enabling the api to be a service to access
    # - "traefik.http.routers.revproxy.service=app@internal" # <== Enabling the app to be a service to access
    # - "traefik.http.routers.revproxy.service=web@internal" # <== Enabling the web to be a service to access
    command:
      # - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      # - "--entrypoints.app.address=:80"

  # ##########
  # # database
  # ##########

  db:
    image: postgres:13.1
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "postgres", "-U", "postgres"]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always

    ports:
      - 5432:5432

    volumes:
      - ./db/data:/var/lib/postgresql/data/

    env_file:
      - ./env/local/db.env

    labels:
      - "traefik.enable=false"

  ##########
  # www
  ##########

  www:
    build:
      context: .
      dockerfile: ./dockerfiles/www.dev.dockerfile
    ports:
      - 3000:3000
    labels:
      - "traefik.http.routers.www.rule=Host(`planandeatwell.localhost`)"
      - "traefik.http.routers.www.entrypoints=web"
      - "traefik.enable=true"

    volumes:
      - ./www:/app
      - ./www/node_modules:/app/node_modules
      - ./www/.next:/app/.next

    env_file:
      - ./env/local/www.env

  ##########
  # app
  ##########

  app:
    build:
      context: .
      dockerfile: ./dockerfiles/app.dev.dockerfile
    ports:
      - 3001:3001
    labels:
      - "traefik.http.routers.app.rule=Host(`app.planandeatwell.localhost`)"
      - "traefik.http.routers.app.entrypoints=web"
      - "traefik.http.services.app.loadbalancer.server.port=3001" # required to update loadbalancer port, as next js running on different port
      - "traefik.enable=true"

    volumes:
      - ./app:/app
      - ./app/node_modules:/app/node_modules
      - ./app/.next:/app/.next

    env_file:
      - ./env/local/app.env

  ##########
  # api
  ##########

  api:
    build:
      context: .
      dockerfile: ./dockerfiles/api.dev.dockerfile
    ports:
      - 4000:4000
    labels:
      - "traefik.http.routers.api.rule=Host(`api.planandeatwell.localhost`)"
      # - "traefik.http.middlewares.api-redirectregex.redirectregex.regex=^http://localhost:4000/(.*)"
      # - "traefik.http.middlewares.api-redirectregex.redirectregex.replacement=http://api.planandeatwell.localhost:4000/$${1}"
      # - "traefik.http.routers.api.middlewares=api-redirectregex@docker"
      - "traefik.enable=true"
    volumes:
      - ./api:/app:delegated
    env_file:
      - ./env/local/api.env

    depends_on:
      db:
        condition: service_healthy
