import { Container, ListItem, UnorderedList } from "@chakra-ui/react";
import Head from "next/head";
import Layout from "../components/layout";
import { Text, Link } from "@chakra-ui/react";
import { forwardRef, Box, TextProps } from "@chakra-ui/react";

const Title = forwardRef<TextProps, "h1">((props, ref) => (
  <Text color="gray.dark" fontSize={"36px"} ref={ref} as={"h1"} {...props} />
));

const Heading = forwardRef<TextProps, "h3">((props, ref) => (
  <Text fontSize={"24px"} ref={ref} as={"h3"} {...props} />
));

const MainText = forwardRef<TextProps, "p">((props, ref) => (
  <Text
    fontSize={"16"}
    color="gray.normal"
    fontWeight={400}
    ref={ref}
    {...props}
  />
));

export default function Privacy() {
  return (
    <Layout>
      <Head>
        <title>Privacy Policy</title>
      </Head>

      <Container
        maxW="1200px"
        mt={"5rem"}
        mb={20}
        sx={{ position: "relative" }}
      >
        <Box mb={5}>
          <Title mb={2}>Privacy Policy</Title>
          <MainText>
            Effective date: Sep 28, 2022
            <br />
            <br />
            New Stack Limited (&quot;us&quot;, &quot;we&quot;, or
            &quot;our&quot;) operates the planandeatwell.uk website (hereinafter
            referred to as the &quot;Service&quot;). This page informs you of
            our policies regarding the collection, use and disclosure of
            personal data when you use our Service and the choices you have
            associated with that data. We use your data to provide and improve
            the Service. By using the Service, you agree to the collection and
            use of information in accordance with this policy. Unless otherwise
            defined in this Privacy Policy, the terms used in this Privacy
            Policy have the same meanings as in our Terms and Conditions,
            accessible from planandeatwell.uk
          </MainText>
        </Box>

        <Box mb={5}>
          <Heading mb={2}>Definitions</Heading>

          <>
            <MainText fontWeight={500} color="gray.dark">
              Service
            </MainText>
            <MainText>
              Service is the planandeatwell.uk website operated by New Stack
              Limited
            </MainText>
          </>

          <>
            <MainText fontWeight={500} color="gray.dark">
              Personal Data
            </MainText>
            <MainText>
              Personal Data means data about a living individual who can be
              identified from those data (or from those and other information
              either in our possession or likely to come into our possession).
            </MainText>
          </>

          <>
            <MainText fontWeight={500} color="gray.dark">
              Usage Data
            </MainText>
            <MainText>
              Usage Data is data collected automatically either generated by the
              use of the Service or from the Service infrastructure itself (for
              example, the duration of a page visit).
            </MainText>
          </>

          <>
            <MainText fontWeight={500} color="gray.dark">
              Cookies
            </MainText>
            <MainText>
              Cookies are small files stored on your device (computer or mobile
              device).
            </MainText>
          </>

          <>
            <MainText fontWeight={500} color="gray.dark">
              Data Controller
            </MainText>
            <MainText>
              Data Controller means the natural or legal person who (either
              alone or jointly or in common with other persons) determines the
              purposes for which and the manner in which any personal
              information are, or are to be, processed. For the purpose of this
              Privacy Policy, we are a Data Controller of your Personal Data.
            </MainText>
          </>

          <>
            <MainText fontWeight={500} color="gray.dark">
              Data Processors (or Service Providers)
            </MainText>
            <MainText>
              Data Processor means any natural or legal person who processes the
              data on behalf of the Data Controller. We may use the services of
              various Service Providers in order to process your data more
              effectively.
            </MainText>
          </>

          <>
            <MainText fontWeight={500} color="gray.dark">
              Data Subject (or User)
            </MainText>
            <MainText>
              Data Subject is any living individual who is using our Service and
              is the subject of Personal Data.
            </MainText>
          </>
        </Box>

        <Box mb={5}>
          <Heading mb={2}>Information Collection and Use</Heading>
          <Heading mb={5} fontSize={"1.25rem"}>
            Types of Data Collected
          </Heading>

          <Box mb={5}>
            <Heading mb={2} fontSize={"1.1rem"}>
              Personal Data
            </Heading>
            <MainText>
              While using our Service, we may ask you to provide us with certain
              personally identifiable information that can be used to contact or
              identify you (&quot;Personal Data&quot;). Personally identifiable
              information may include, but is not limited to:
            </MainText>

            <UnorderedList>
              <ListItem>
                <MainText>Email address</MainText>
              </ListItem>
              <ListItem>
                <MainText>Cookies and Usage Data</MainText>
              </ListItem>
            </UnorderedList>

            <br />

            <MainText>
              We may use your Personal Data to contact you with newsletters,
              marketing or promotional materials and other information that may
              be of interest to you. You may opt out of receiving any, or all,
              of these communications from us by following the unsubscribe link
              or instructions provided in any email we send or by contacting us.
            </MainText>
          </Box>

          <Box mb={5}>
            <Heading mb={2} fontSize={"1.1rem"}>
              Usage Data
            </Heading>
            <MainText>
              We may also collect information on how the Service is accessed and
              used (&quot;Usage Data&quot;). This Usage Data may include
              information such as your computer&#39;s Internet Protocol address
              (e.g. IP address), browser type, browser version, the pages of our
              Service that you visit, the time and date of your visit, the time
              spent on those pages, unique device identifiers and other
              diagnostic data.
            </MainText>
          </Box>

          <Box mb={5}>
            <Heading mb={2} fontSize={"1.1rem"}>
              Tracking & Cookies Data
            </Heading>
            <MainText>
              We use cookies and similar tracking technologies to track the
              activity on our Service and we hold certain information. Cookies
              are files with a small amount of data which may include an
              anonymous unique identifier. Cookies are sent to your browser from
              a website and stored on your device. Other tracking technologies
              are also used such as beacons, tags and scripts to collect and
              track information and to improve and analyse our Service. You can
              instruct your browser to refuse all cookies or to indicate when a
              cookie is being sent. However, if you do not accept cookies, you
              may not be able to use some portions of our Service. Examples of
              Cookies we use: <br />
              <MainText fontWeight={500} color="gray.dark" as={"span"}>
                Session Cookies
              </MainText>
              . We use Session Cookies to operate our Service.
              <br />
              <MainText fontWeight={500} color="gray.dark" as={"span"}>
                Preference Cookies
              </MainText>
              . We use Preference Cookies to remember your preferences and
              various settings.
              <br />
              <MainText fontWeight={500} color="gray.dark" as={"span"}>
                Security Cookies
              </MainText>
              . We use Security Cookies for security purposes.
            </MainText>
          </Box>
        </Box>

        <Box mb={5}>
          <Heading mb={2}>Use of Data</Heading>
          <MainText>
            Plan and Eat Well uses the collected data for various purposes:
            <br />
            To provide and maintain our Service
            <br /> To notify you about changes to our Service
            <br /> To allow you to participate in interactive features of our
            Service when you choose to do so <br />
            To provide customer support
            <br /> To gather analysis or valuable information so that we can
            improve our Service To monitor the usage of our Service
            <br /> To detect, prevent and address technical issues
            <br /> To provide you with news, special offers and general
            information about other goods, services and events which we offer
            that are similar to those that you have already purchased or
            enquired about unless you have opted not to receive such information
            <br />
          </MainText>
        </Box>

        <Box mb={5}>
          <Heading mb={2}>
            Legal Basis for Processing Personal Data under the General Data
            Protection Regulation (GDPR)
          </Heading>
          <MainText>
            If you are from the European Economic Area (EEA), Plan and Eat Well
            legal basis for collecting and using the personal information
            described in this Privacy Policy depends on the Personal Data we
            collect and the specific context in which we collect it. <br />
            <br />
            Plan and Eat Well may process your Personal Data because:
            <br />
            We need to perform a contract with you <br />
            You have given us permission to do so <br />
            The processing is in our legitimate interests and it is not
            overridden by your rights <br />
            For payment processing purposes <br />
            To comply with the law
          </MainText>
        </Box>

        <Box mb={5}>
          <Heading mb={2}>Retention of Data</Heading>
          <MainText>
            Plan and Eat Well will retain your Personal Data only for as long as
            is necessary for the purposes set out in this Privacy Policy. We
            will retain and use your Personal Data to the extent necessary to
            comply with our legal obligations (for example, if we are required
            to retain your data to comply with applicable laws), resolve
            disputes and enforce our legal agreements and policies. <br />
            <br />
            Plan and Eat Well will also retain Usage Data for internal analysis
            purposes. Usage Data is generally retained for a shorter period of
            time, except when this data is used to strengthen the security or to
            improve the functionality of our Service, or we are legally
            obligated to retain this data for longer periods.
          </MainText>
        </Box>

        <Box mb={5}>
          <Heading mb={2}>Transfer of Data</Heading>
          <MainText>
            Your information, including Personal Data, may be transferred to -
            and maintained on - computers located outside of your state,
            province, country or other governmental jurisdiction where the data
            protection laws may differ from those of your jurisdiction. <br />
            <br />
            If you are located outside Europe (UK) and choose to provide
            information to us, please note that we transfer the data, including
            Personal Data, to Europe (UK) and process it there. <br />
            <br />
            Your consent to this Privacy Policy followed by your submission of
            such information represents your agreement to that transfer. <br />
            <br />
            Plan and Eat Well will take all the steps reasonably necessary to
            ensure that your data is treated securely and in accordance with
            this Privacy Policy and no transfer of your Personal Data will take
            place to an organisation or a country unless there are adequate
            controls in place including the security of your data and other
            personal information.
          </MainText>
        </Box>

        <Box mb={5}>
          <Heading mb={2}>Disclosure of Data</Heading>

          <Box mb={5}>
            <Heading mb={5} fontSize={"1.25rem"}>
              Business Transaction
            </Heading>
            <MainText>
              If Plan and Eat Well is involved in a merger, acquisition or asset
              sale, your Personal Data may be transferred. We will provide
              notice before your Personal Data is transferred and becomes
              subject to a different Privacy Policy.
            </MainText>
          </Box>

          <Box mb={5}>
            <Heading mb={5} fontSize={"1.25rem"}>
              Disclosure for Law Enforcement
            </Heading>
            <MainText>
              Under certain circumstances, Plan and Eat Well may be required to
              disclose your Personal Data if required to do so by law or in
              response to valid requests by public authorities (e.g. a court or
              a government agency).
            </MainText>
          </Box>

          <Box mb={5}>
            <Heading mb={5} fontSize={"1.25rem"}>
              Legal Requirements
            </Heading>
            <MainText>
              Plan and Eat Well may disclose your Personal Data in the good
              faith belief that such action is necessary to:
              <br />
              <br /> To comply with a legal obligation
              <br /> To protect and defend the rights or property of Plan and
              Eat Well
              <br /> To prevent or investigate possible wrongdoing in connection
              with the Service
              <br /> To protect the personal safety of users of the Service or
              the public
              <br /> To protect against legal liability
            </MainText>
          </Box>
        </Box>

        <Box mb={5}>
          <Heading mb={2}>Security of Data</Heading>
          <MainText>
            The security of your data is important to us but remember that no
            method of transmission over the Internet or method of electronic
            storage is 100% secure. While we strive to use commercially
            acceptable means to protect your Personal Data, we cannot guarantee
            its absolute security.
          </MainText>
        </Box>

        <Box mb={5}>
          <Heading mb={2}>
            Your Data Protection Rights under the General Data Protection
            Regulation (GDPR)
          </Heading>
          <MainText>
            If you are a resident of the European Economic Area (EEA), you have
            certain data protection rights. Plan and Eat Well aims to take
            reasonable steps to allow you to correct, amend, delete or limit the
            use of your Personal Data.
            <br />
            <br /> If you wish to be informed about what Personal Data we hold
            about you and if you want it to be removed from our systems, please
            contact us. <br />
            <br />
            In certain circumstances, you have the following data protection
            rights: <br />
            <br />
            <MainText fontWeight={500} color="gray.dark" as={"span"}>
              The right to access, update or delete the information we have on
              you.&nbsp;
            </MainText>
            Whenever made possible, you can access, update or request deletion
            of your Personal Data directly within your account settings section.
            If you are unable to perform these actions yourself, please contact
            us to assist you. <br />
            <MainText fontWeight={500} color="gray.dark" as={"span"}>
              The right of rectification.&nbsp;
            </MainText>
            You have the right to have your information rectified if that
            information is inaccurate or incomplete. <br />
            <MainText fontWeight={500} color="gray.dark" as={"span"}>
              The right to object.&nbsp;
            </MainText>
            You have the right to object to our processing of your Personal
            Data. <br />
            <MainText fontWeight={500} color="gray.dark" as={"span"}>
              The right of restriction.&nbsp;
            </MainText>
            You have the right to request that we restrict the processing of
            your personal information.
            <br />
            <MainText fontWeight={500} color="gray.dark" as={"span"}>
              The right to data portability.&nbsp;
            </MainText>
            You have the right to be provided with a copy of the information we
            have on you in a structured, machine-readable and commonly used
            format.
            <br />
            <MainText fontWeight={500} color="gray.dark" as={"span"}>
              The right to withdraw consent.&nbsp;
            </MainText>
            You also have the right to withdraw your consent at any time where
            Plan and Eat Well relied on your consent to process your personal
            information.
            <br />
            <br /> Please note that we may ask you to verify your identity
            before responding to such requests. <br />
            <br />
            You have the right to complain to a Data Protection Authority about
            our collection and use of your Personal Data. For more information,
            please contact your local data protection authority in the European
            Economic Area (EEA).
          </MainText>
        </Box>

        <Box mb={5}>
          <Heading mb={2}>Service Providers</Heading>
          <MainText mb={5}>
            We may employ third party companies and individuals to facilitate
            our Service (&quot;Service Providers&quot;), provide the Service on
            our behalf, perform Service-related services or assist us in
            analysing how our Service is used. These third parties have access
            to your Personal Data only to perform these tasks on our behalf and
            are obligated not to disclose or use it for any other purpose.
          </MainText>

          <Box mb={5}>
            <Heading mb={5} fontSize={"1.25rem"}>
              Analytics
            </Heading>
            <MainText>
              We may use third-party Service Providers to monitor and analyse
              the use of our Service.
            </MainText>
          </Box>
        </Box>

        <Box mb={5}>
          <Heading mb={2}>Links to Other Sites</Heading>
          <MainText>
            Our Service may contain links to other sites that are not operated
            by us. If you click a third party link, you will be directed to that
            third party&#39;s site. We strongly advise you to review the Privacy
            Policy of every site you visit. <br />
            <br /> We have no control over and assume no responsibility for the
            content, privacy policies or practices of any third party sites or
            services.
          </MainText>
        </Box>

        <Box mb={5}>
          <Heading mb={2}>Children&#39;s Privacy</Heading>
          <MainText>
            Our Service does not address anyone under the age of 18
            (&quot;Children&quot;). <br />
            <br />
            We do not knowingly collect personally identifiable information from
            anyone under the age of 18. If you are a parent or guardian and you
            are aware that your Child has provided us with Personal Data, please
            contact us. If we become aware that we have collected Personal Data
            from children without verification of parental consent, we take
            steps to remove that information from our servers.
          </MainText>
        </Box>

        <Box mb={5}>
          <Heading mb={2}>Changes to This Privacy Policy</Heading>
          <MainText>
            We may update our Privacy Policy from time to time. We will notify
            you of any changes by posting the new Privacy Policy on this page.
            <br />
            <br />
            We will let you know via email and/or a prominent notice on our
            Service, prior to the change becoming effective and update the
            &quot;effective date&quot; at the top of this Privacy Policy.
            <br />
            <br /> You are advised to review this Privacy Policy periodically
            for any changes. Changes to this Privacy Policy are effective when
            they are posted on this page.
          </MainText>
        </Box>

        <Box mb={5}>
          <Heading mb={2}>Contact Us</Heading>
          <MainText>
            If you have any questions about these terms, please contact us:
            <br /> By email:&nbsp;
            <Link
              fontWeight={500}
              href="mailto:support@planandeatwell.uk"
              isExternal
            >
              support@planandeatwell.uk
            </Link>
          </MainText>
        </Box>
      </Container>
    </Layout>
  );
}
