name: 'Build and deploy to production'

on:
  push:
    branches:
      - prod
  # pull_request:
  #   branches:
  #     - prod

jobs:
  db-migrations: 
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup node 
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install global Dependencies
        working-directory: ./api
        run: | 
            npm i

      - name: Run migration
        working-directory: ./api
        run: NODE_ENV=production DATABASE_URL=${{ secrets.DB_PROD_URL }} npm run migrate:latest

  api-deploy: 
    needs: [db-migrations]
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up qemu
        uses: docker/setup-qemu-action@v2

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: build_and_push_api
        uses: docker/build-push-action@v3
        with:
          file: dockerfiles/api.dockerfile
          push: true
          tags: fincht96/api-prod-planandeatwell:latest

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_push_flags: '--force'
          git_remote_url: 'ssh://dokku@${{ secrets.DOKKU_IP }}:22/planandeatwell-api-prod'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          deploy_docker_image: fincht96/api-prod-planandeatwell:latest@${{ steps.build_and_push_api.outputs.digest }}

  www-deploy:
    needs: [api-deploy]
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up qemu
        uses: docker/setup-qemu-action@v2

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: build_and_push_www
        uses: docker/build-push-action@v3
        with:
          file: dockerfiles/www.dockerfile
          push: true
          tags: fincht96/www-prod-planandeatwell:latest
          build-args: |
            NEXT_PUBLIC_API_URL=${{vars.NEXT_PUBLIC_API_URL}} 
            NEXT_PUBLIC_GA_TRACKING_ID=${{ vars.NEXT_PUBLIC_GA_TRACKING_ID }} 
            NEXT_PUBLIC_ENV=${{ vars.NEXT_PUBLIC_ENV }} 
            NEXT_PUBLIC_CDN=${{ vars.NEXT_PUBLIC_CDN }} 
            NEXT_PUBLIC_WWW_URL=${{ vars.NEXT_PUBLIC_WWW_URL }}
            NEXT_PUBLIC_APP_BASE_URL=${{ vars.NEXT_PUBLIC_APP_BASE_URL }}
            NEXT_PUBLIC_API_URL_DOCKER_SERVICE=${{ vars.NEXT_PUBLIC_API_URL_DOCKER_SERVICE }}
           


      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_push_flags: '--force'
          git_remote_url: 'ssh://dokku@${{ secrets.DOKKU_IP }}:22/planandeatwell-www-prod'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          deploy_docker_image: fincht96/www-prod-planandeatwell:latest@${{ steps.build_and_push_www.outputs.digest }}
          
  app-deploy:
    needs: [api-deploy]
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up qemu
        uses: docker/setup-qemu-action@v2

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: build_and_push_app
        uses: docker/build-push-action@v3
        with:
          file: dockerfiles/app.dockerfile
          push: true
          tags: fincht96/app-prod-planandeatwell:latest
          build-args: |
            NEXT_PUBLIC_WWW_URL=${{ vars.NEXT_PUBLIC_WWW_URL }}
            NEXT_PUBLIC_API_URL=${{ vars.NEXT_PUBLIC_API_URL }}
            NEXT_PUBLIC_GA_TRACKING_ID=${{ vars.NEXT_PUBLIC_GA_TRACKING_ID }}
            NEXT_PUBLIC_ENV=${{ vars.NEXT_PUBLIC_ENV }}
            NEXT_PUBLIC_CDN=${{ vars.NEXT_PUBLIC_CDN }}
            NEXT_PUBLIC_FIREBASE_API_KEY=${{ vars.NEXT_PUBLIC_FIREBASE_API_KEY }}
            NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${{ vars.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
            NEXT_PUBLIC_FIREBASE_PROJECT_ID=${{ vars.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
            NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${{ vars.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}
            NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${{ vars.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
            NEXT_PUBLIC_FIREBASE_APP_ID=${{ vars.NEXT_PUBLIC_FIREBASE_APP_ID }}


      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_push_flags: '--force'
          git_remote_url: 'ssh://dokku@${{ secrets.DOKKU_IP }}:22/planandeatwell-app-prod'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          deploy_docker_image: fincht96/app-prod-planandeatwell:latest@${{ steps.build_and_push_app.outputs.digest }}

  admin-deploy:
    needs: [api-deploy]
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up qemu
        uses: docker/setup-qemu-action@v2

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: build_and_push_admin
        uses: docker/build-push-action@v3
        with:
          file: dockerfiles/admin.dockerfile
          push: true
          tags: fincht96/admin-prod-planandeatwell:latest
          build-args: |
            NEXT_PUBLIC_API_URL=${{ vars.NEXT_PUBLIC_API_URL }}
            NEXT_PUBLIC_FIREBASE_API_KEY=${{ vars.NEXT_PUBLIC_FIREBASE_API_KEY }}
            NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${{ vars.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
            NEXT_PUBLIC_FIREBASE_PROJECT_ID=${{ vars.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
            NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${{ vars.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}
            NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${{ vars.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
            NEXT_PUBLIC_FIREBASE_APP_ID=${{ vars.NEXT_PUBLIC_FIREBASE_APP_ID }}


      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_push_flags: '--force'
          git_remote_url: 'ssh://dokku@${{ secrets.DOKKU_IP }}:22/planandeatwell-admin-prod'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          deploy_docker_image: fincht96/admin-prod-planandeatwell:latest@${{ steps.build_and_push_admin.outputs.digest }}



#  to do run migrations